<?php

namespace Unikronn\CitasMedicasBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Tipo_citaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Tipo_citaRepository extends EntityRepository
{
}
